kind: ConfigMap
apiVersion: v1
metadata:
  name: app-env
  namespace: work-in-france-backoffice
data:
  MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
  YOUTUBE_API_URL: https://youtube.googleapis.com/youtube/v3/
  YOUTUBE_CHANNEL_ID: UClDwrT-Y1NY9WnEiXLMHp6w
  GITHUB_API_URL: https://api.github.com
  TYPEFORM_API_URL: https://api.typeform.com
  CORS_ORIGINS: "*"
